resources:
  - ../../base
patchesStrategicMerge:
  - replica_count.yaml
  - deployment_patch.yaml
commonLabels:
  env: production  # Label applied to every resource
namePrefix: prod-  # Prefix added to the name of all resources