apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opeyemiogungbe/gitops-app-deployment.git
    targetRevision: staging
    path: overlay/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
