apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opeyemiogungbe/gitops-app-deployment.git
    targetRevision: dev
    path: overlay/dev
  destination:
    # Replace with the name of the dev cluster registered in Argo CD
    name: dev-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
