resources:
  - deployment.yaml
  - service.yaml
  - aws-credentials-secret.yaml
  - secret-store.yaml
  - external-secret.yaml
  - rbac.yaml
  - oauth.yaml

configMapGenerator:
- name: my-configmap  # Name of the ConfigMap
  literals:
  - key1=value1       # Key-value pairs
  - key2=value2
- name: my-app-config
  literals:
  - app_name=MyKustomizeApp
  - log_level=debug

generatorOptions:
  disableNameSuffixHash: true