replicaCount: 0

image:
  repository: nginx
  tag: latest

service:
  type: ClusterIP
  port: 80

env:
  APP_ENV: dev

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false